#!/usr/bin/env php
<?php

use beemaker\Install;
use beemaker\Model;
use beemaker\Table;
use beemaker\Utils;

if (php_sapi_name() !== 'cli') {
    die("Usar: php beemaker");
}

include $_composer_autoload_path ?? __DIR__ . '/vendor/autoload.php';

$app = new beemaker($argv);

final class Beemaker
{
    const VERSION = '1.0';
    const OK = " -> OK.\n";

    public function __construct($argv)
    {
        if (count($argv) < 2) {
            $this->help();
            return;
        }

        Utils::setFolder(__DIR__);

        switch ($argv[1]) {
            case 'install':
                $install = new Install();
                $install->newInstalation();
                break;

            case 'table':
                $table = new Table();
                $table->createTable();
                break;

            case 'model':
                $model = new Model();
                $model->createModel();
                break;

            case 'help':
            default:
                $this->help();
                break;
        }
    }

    private function help(): void
    {
            echo("\n\033[34mBeeFramework Maker v\033[33m" . self::VERSION . "\033[0m\n\n"
                . "crear:\n"
                . "\033[32m$ beemaker\033[33m install\n"
                . "\033[32m$ beemaker\033[33m table\n"
                . "\033[32m$ beemaker\033[33m model (El Modelo crea su propia tabla)\n"
                . "\033[32m$ beemaker\033[33m controller\n\n\033[0m");
    }
}